"""added address1 and address2 colums

Revision ID: 0882105a2d79
Revises: a96825922839
Create Date: 2021-03-24 19:34:03.250229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0882105a2d79'
down_revision = 'a96825922839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address1', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('address2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address2')
    op.drop_column('user', 'address1')
    # ### end Alembic commands ###
