"""added new table Post

Revision ID: 08e4313bfd01
Revises: 52f8dcdff537
Create Date: 2021-04-04 21:48:09.076197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e4313bfd01'
down_revision = '52f8dcdff537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
