"""mot sure

Revision ID: 1e5eda06b56a
Revises: 26f449188eb7
Create Date: 2021-04-04 22:03:41.935712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5eda06b56a'
down_revision = '26f449188eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_1')
    op.drop_column('product', 'image_3')
    op.drop_column('product', 'image_main')
    op.drop_column('product', 'image_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_2', sa.VARCHAR(length=50), nullable=False))
    op.add_column('product', sa.Column('image_main', sa.VARCHAR(length=50), nullable=False))
    op.add_column('product', sa.Column('image_3', sa.VARCHAR(length=50), nullable=False))
    op.add_column('product', sa.Column('image_1', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
