"""add new first_name column

Revision ID: 2365de670392
Revises: e659f4bb8bb5
Create Date: 2021-03-24 18:02:28.105608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2365de670392'
down_revision = 'e659f4bb8bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
