"""fixed column names.

Revision ID: 432b342fd814
Revises: abb1e4185700
Create Date: 2021-04-02 00:08:35.997561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432b342fd814'
down_revision = 'abb1e4185700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'brand_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('brand_name', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
