"""added new table Post

Revision ID: 591fc6bafd53
Revises: 08e4313bfd01
Create Date: 2021-04-04 21:49:37.480347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591fc6bafd53'
down_revision = '08e4313bfd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
