"""not sure.

Revision ID: 5aae4734e88c
Revises: fb8d34afc3b2
Create Date: 2021-03-25 21:18:20.744681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aae4734e88c'
down_revision = 'fb8d34afc3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'confirmed_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_on', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
