"""updated the product table with images clumns.

Revision ID: 72a6f9f33735
Revises: 8701af91f762
Create Date: 2021-04-02 12:30:52.199199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a6f9f33735'
down_revision = '8701af91f762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_1', sa.String(length=50), nullable=False))
    op.add_column('product', sa.Column('image_2', sa.String(length=50), nullable=False))
    op.add_column('product', sa.Column('image_3', sa.String(length=50), nullable=False))
    op.add_column('product', sa.Column('image_main', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_main')
    op.drop_column('product', 'image_3')
    op.drop_column('product', 'image_2')
    op.drop_column('product', 'image_1')
    # ### end Alembic commands ###
