"""fixed column name brand_name.

Revision ID: 76b805943c88
Revises: 976da80a150b
Create Date: 2021-04-02 00:19:14.928634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b805943c88'
down_revision = '976da80a150b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'brand_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('brand_name', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
