"""fixed column names.

Revision ID: 976da80a150b
Revises: 432b342fd814
Create Date: 2021-04-02 00:15:53.740415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976da80a150b'
down_revision = '432b342fd814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'brand_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('brand_name', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
