"""added country column

Revision ID: a96825922839
Revises: 20dad35e4964
Create Date: 2021-03-24 19:19:44.764882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96825922839'
down_revision = '20dad35e4964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sqlalchemy_utils.types.country.CountryType(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
